/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AnagramFinderTemplate_Java;

public class AnagramFinder {
    public static void main(String[] args) {
       //TODO
    }

    public List<List<String>> findAllAnagrams(List<String> wordList) throws IllegalArgumentException{
        //TODO
    }

}
