/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AnagramFinderTemplate_Java;

import java.util.*;

public class AnagramFinder {
    public static void main(String[] args) {

    }

    public static List< List<String> > findAllAnagrams(List<String> wordList) throws IllegalArgumentException{

    }

}
